version: "3"
services:

    shorturl:
        image: golang
        volumes:
         - ./:/go/src/ShortURL
        working_dir: /go/src/ShortURL
        ports:
         - "18080:8080"
        command: ./run.sh
